# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, upload_to='org_logo'),
        ),
    ]
