# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='venue',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
