# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orgsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgsite', '0002_organization_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='image',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to=orgsite.models.logo_upload_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
